Objetivo 6 [IV-21-22]
amerigal/gestor-recibos pull request #31
Opened 2021-11-23 23:28 UTC by amerigal

Progreso realizado en el objetivo 6:

- Elección de servicio de IC (#30)
- Configuración para ejecución automática de tests (#29)
- Documentación actualizada.
- Hito 3 finalizado.

2021-11-23 23:42 UTC, amerigal commented
Listo para revisión. @JJ

2021-11-26 23:36 UTC, amerigal commented
Modificaciones referentes a las actualizaciones del guión añadidas:
- Checks API configurado.
- Comprobación de versiones de go válidas realizada (la 1.16 y 1.17 son las dos versiones estables actualmente).
- Clave CI añadida.

Listo para revisión. @JJ

2021-11-28 11:39 UTC, JJ requested changes
Sólo has configurado un sistema. En ese ejecutas dos jobs, cuando los dos usan la misma máquina, así que estás repitiendo cosas innecesarias. Aclara también lo que haces, y justifica los CI elegidos.

2021-11-28 11:39 UTC, JJ commented on .circleci/config.yml
> +        - run: docker run -t -v `pwd`:/app/test -w="/app/test" cimg/go:<< parameters.version >> go build -v -o /dev/null pkg/*/*
¿Por qué haces esto? ¿Para compilar?

2021-11-28 11:39 UTC, JJ commented on .circleci/config.yml
> +        - run: docker run -t -v `pwd`:/app/test -w="/app/test" cimg/go:<< parameters.version >> go build -v -o /dev/null pkg/*/*
¿Sólo comprueba una versión?

2021-11-28 11:40 UTC, JJ commented
Refiérete al issue correspondiente en todos los commits relevantes, por favor.

2021-11-28 15:52 UTC, amerigal commented
Listo para revisión @JJ.

He configurado un segundo sistema migrando uno de los jobs a GitHub Actions y he ampliado la documentación del objetivo explicando las tareas desarrolladas y contestando a las preguntas planteadas.

2021-11-28 15:59 UTC, amerigal commented on .circleci/config.yml
> +        - run: docker run -t -v `pwd`:/app/test -w="/app/test" cimg/go:<< parameters.version >> go build -v -o /dev/null pkg/*/*
Espero que quede más claro con la documentación que acabo de añadir, pero sí, lo que realizo es una compilación y no se comprueba una sola versión, sino que habrá un job por cada una de las versiones incluidas en la lista en que toma valores el parámetro version.

2021-11-28 18:58 UTC, JJ commented on .circleci/config.yml
> +        - run: docker run -t -v `pwd`:/app/test -w="/app/test" cimg/go:<< parameters.version >> go build -v -o /dev/null pkg/*/*
La verdad es que la concurrencia de Go es una maravilla... Pero realmente lo que quería que probárais es la capacidad de los sistemas de CI para probar varias versiones de cosas. Si quieres probar versiones de Go y de Ubuntu, por ejemplo, no vas a poder hacer esto (o no a la vez)

2021-11-28 18:59 UTC, JJ reviewed
:+1:

2021-11-28 20:49 UTC, amerigal commented on .circleci/config.yml
> +        - run: docker run -t -v `pwd`:/app/test -w="/app/test" cimg/go:<< parameters.version >> go build -v -o /dev/null pkg/*/*
En realidad diría que no tiene que ver con la concurrencia de Go, creo que no me he explicado bien. Básicamente he hecho uso de los workflows de Circle-CI, que permiten definir una "matrix" para contemplar todas las combinaciones de diferentes parámetros. En mi caso solo he variado los valores de la versión de go, que aparecen en el workflow definido debajo del job, pero entiendo que se podría parametrizar también la versión de ubuntu con la que trabajar al estilo del ejemplo que hay aquí: https://circleci.com/blog/circleci-matrix-jobs/

2021-11-28 20:51 UTC, merged